### ISSUE TITLE
Announcement feature announcing wrong time left

### ISSUE THREAD

**Issue by YourHuckleberry** [prom3theu5/ConanExilesServerUpdater#1]
With "AnnouncementMinutesBefore" set to 1, my discord bot announces restart in five minutes, and then shuts down the server a minute later for the update.

**Comment by prom3theu5** [comment]
Thanks - fixed :)
Please grab release 1.2 from [here](https://github.com/prom3theu5/ConanExilesServerUpdater/releases/download/1.2/1.2.zip)
