### ISSUE TITLE
suggestion/question

### ISSUE THREAD

**Issue by DirtyNightmare** [prom3theu5/ConanExilesServerUpdater#13]
is it possible to add a function to post a message on Teamspeak when there is an update

and also how does the raid protection works?
lets say i wanna turn raiding off from 00.00 until 10.00 how do you do that

**Comment by prom3theu5** [comment]
To turn raiding off between those hours put put start time as 10, and number of hours as 14 :)

I'll look into TS for you

**Comment by hnomkeng** [comment]
how to setup open fuction auto restart on crash only ?

**Comment by prom3theu5** [comment]
"ShouldRestartConanOnNotRunning": true,

That will restart the server on a crash, but you still need to setup your paths - try to match the example on the first page where you can - apart from your individual startup parameters :)

**Comment by hnomkeng** [comment]
i don't see config.json file @prom3theu5

**Comment by prom3theu5** [comment]
it's in the same folder as the application, and if it isn't present - when you run the application it will create the file with empty / default values

```
{
  "Twitch": {
    "OAuth": "",
    "Username": "",
    "Channel": 0
  },
  "Discord": {
    "DiscordToken": "",
    "ChannelId": 0
  },
  "Conan": {
    "FolderPath": "c:\\conanserver\\",
    "Executable": "ConanSandboxServer.exe",
    "StartupParameters": "ConanSandbox?Multihome=X.X.X.X?GameServerPort=27015?GameServerQueryPort=27016?ServerName=YOURSERVERNAME?MaxPlayers=50?listen?AdminPassword=YOURADMINPASSWORD -nosteamclient -game -server",
    "RaidingProtectionHoursEnabled": false,
    "RaidingStartHour": 0,
    "RaidingLengthInHours": 0,
    "AvatarsEnabledCertainHours": false,
    "AvatarActivationHour": 0,
    "AvatarsActiveLengthInHours": 0
  },
  "Update": {
    "ShouldInstallSteamCmdIfMissing": false,
    "ShouldInstallConanServerIfMissing": false,
    "SteamCmdPath": "c:\\steamcmd\\",
    "AnnounceDiscord": false,
    "AnnounceTwitch": false,
    "AnnounceMinutesBefore": 5,
    "UpdateCheckInterval": 5,
    "InstalledBuild": 0,
    "UpdateOnLaunch": true
  },
  "General": {
    "ShouldRestartConanOnNotRunning": true,
    "RestartServerAfterHours": 0
  }
}
```

That is the contents of the file, just an example.
You have to make sure you are using the latest version of the application, otherwise if you are running the app as a service, and not double clicking, then the config.json file could be present in c:\windows\syswow64
