### ISSUE TITLE
Help set the update files

### ISSUE THREAD

**Issue by Brolicious** [prom3theu5/ConanExilesServerUpdater#19]
Hey man! 
Sorry to ask, im kinda new into setting this files onto the server... atm ive configured the paths of the conan server and the exe file and set a time for an autoupdate, whenever a new version comes up, but when a new version came up, the serv didnt update automatically... 

on the log i got this messages> 

2017-02-23 23:156.023 +010 [Information] Stopping the "ConanExilesUpdater$ConanExilesUpdater" service
2017-02-23 23:156.026 +010 [Information] The "ConanExilesUpdater$ConanExilesUpdater" service has stopped.

I dont know why but the service is being stopped and it does not auto restart nor update, i dont know if you could help me set up some of the files

Just to let you know what i did:
ive changed the path of
 "FolderPath": "my server folder path",
   "Executable": " and here ive tried putting only the name of the exe, and then the whole addres of the exe" (like this: "C:\\conanserver2\\ConanSandbox\\Binaries\\Win64\\ConanSandboxServer-Win64-Test.exe"
and then only like this: "ConanSandboxServer-Win64-Test.exe" )

im having some trouble with it, hope you can help me, as I said, its kind of my first servers ive set up

**Comment by prom3theu5** [comment]
Hi Buddy

No problem, there is definitely an error in your config.json file somewhere if the app is instantly stopping like that

Using your example there, it would be the following settings:

```
FolderPath:"C:\\conanserver2\\",
Executable:"ConanSandboxServer.exe"
```

**Comment by Brolicious** [comment]
So taking the example listed above, it would be something like this?

FolderPath: "\\conanserver2\\",
Executable:"conansanboxserver-win64-test.exe" (thats whats my exe is called inside my binaries folder)

Like this? 
Or just the text "conansandboxserver.exe"

**Comment by prom3theu5** [comment]
No no - change it to exactly what I put - so:

```
FolderPath:"C:\\conanserver2\\",
Executable:"ConanSandboxServer.exe"
```

There is also the executable ConanSandBoxServer.exe which will launch the server, inside the server's root directory
