### ISSUE TITLE
Auto server restart not happening

### ISSUE THREAD

**Issue by YourHuckleberry** [prom3theu5/ConanExilesServerUpdater#2]
If I start CESU without the server executable running, it will notice in short order and start it up - But if I CTRL-C the server application, it doesn't start it back up.  Been offline for about 7 minutes now.
It did an update check, but never noticed the server wasn't there.

**Comment by prom3theu5** [comment]
Can you check task manager after closing the server with Control + C
Is there still an executable named ConanSandBoxServer.exe running after the server has closed?
I think i'm going to have to use the other executable for the server, not the wrapper.

Thanks

**Comment by YourHuckleberry** [comment]
Nothing there, hrm.
![image](https://cloud.githubusercontent.com/assets/5511530/22742477/dcc8f48c-ede4-11e6-98f0-b16ae05e95e2.png)

**Comment by YourHuckleberry** [comment]
I have VS on this server, I can try to run it through the debugger to see what is happening a bit later.

**Comment by prom3theu5** [comment]
Cool - I can check more when I am back from work tonight

**Comment by prom3theu5** [comment]
Issue was return inside a while loop,
Should have been continue :/
Not enough Coffee :P

All sorted in the new version, which also offers auto downloads of steamcmd and conan server if not detected in specified folders.

[New Release](https://github.com/prom3theu5/ConanExilesServerUpdater/releases/download/1.3/1.3.zip)
