### ISSUE TITLE
Exception ocoured in detection update server 2012 r2

### ISSUE THREAD

**Issue by DirtyNightmare** [prom3theu5/ConanExilesServerUpdater#22]
so i have a issue with 
`Exception ocoured in detection update: access to the path 'appinfo.vdf' is denied`
the user have admin rights and uac is off

**Comment by ghost** [comment]
Unhandled exception error:  http://imgur.com/JBRwN6N
Also windows server 2012 r2

**Comment by DirtyNightmare** [comment]
@VeronicaMori i had the simmilar issue that was because i didn't used double slashes you have to use it like this
`"SteamCmdPath": "E:\\Tools\\SteamCMD\\",`

**Comment by prom3theu5** [comment]
Yep thats right - that issue is because the slashes aren't escaped in the json config file :)
