### ISSUE TITLE
Conan server can't start through ExilerServerUpdater

### ISSUE THREAD

**Issue by soerenwa** [prom3theu5/ConanExilesServerUpdater#4]
as title say my server wont start through updater. Starting through my cmdscript  still works fine. 

[2017.02.09-13.47.22:541][  0]LogLoad: Took 15.897878 seconds to LoadMap(/Game/Maps/ConanSandbox/ConanSandbox)
[2017.02.09-13.47.22:570][  1]LogOnline:Error: Failed to bind listen socket to addr (0.76.197.233:14001) for LAN beacon
[2017.02.09-13.47.22:573][  1]LogOnline:Warning: Failed to init to LAN beacon 

logs attached.

[cmdlog.txt](https://github.com/prom3theu5/ConanExilesServerUpdater/files/763846/cmdlog.txt)
[conansrvcmd.txt](https://github.com/prom3theu5/ConanExilesServerUpdater/files/763845/conansrvcmd.txt)
[exileupdater_errorlog.txt](https://github.com/prom3theu5/ConanExilesServerUpdater/files/763844/exileupdater_errorlog.txt)

**Comment by YourHuckleberry** [comment]
Based on the log file, something is already running on port 7777.  I'd check your process list for any ghost copies of the server running.

**Comment by soerenwa** [comment]
checked it with netstat -a. nothing open on 7777. Its just with your updater, starting it with cmd directly afterwards works out.

**Comment by prom3theu5** [comment]
Can you confirm that you have correctly changed the StartupParameters option in the config.json file to match the settings you have changed in your startup cmd file?
Inside config.json, find the line:

StartupParameters="ConanSandBox?Multihome=%IP%?GameServerPort=%GamePort%?GameServerQueryPort=%QueryPort%?MaxPlayers=%MaxPlayers%?listen?AdminPassword=%AdminPass%"

In that, Change

```
%IP%,
%GamePort%,
%QueryPort%,
%MaxPlayers%
%AdminPass%
```

to match the values from your batch file:

```
::Set the IP for the Server.
SET IP=144.myip

::Set the Game Port for the Server (This is what players will connect to)
SET GamePort=7777

::Set the Query Port for the Server (Admin purposes? Not sure yet)
SET QueryPort=7778

::Set the Maximum Players Allowed on your server.
SET MaxPlayers=40

::Set the Admin Password. This is what you will use to get administrator rights from the menu.
SET AdminPass=mypw
```

**Comment by soerenwa** [comment]
[config.txt](https://github.com/prom3theu5/ConanExilesServerUpdater/files/763978/config.txt)
"StartupParameters": "ConanSandbox?Multihome=#publicip#?GameServerPort=7777?GameServerQueryPort=7778?MaxPlayers=40?listen?AdminPassword=#mypw#?ServerPassword=##"

**Comment by prom3theu5** [comment]
Are you sure you are typing your ip address in correctly. Looking at the actual error in the first message, you are trying to bind to

IP: 0.76.197.233
Port: 14001

**Comment by prom3theu5** [comment]
Also - the batch file says
SET IP=144.myip
Which is 144.(the rest of your ip)

Try setting your ip (or multihome) to 144.(the rest of your IP)
So if the server log is correct, 144.76.197.233

**Comment by soerenwa** [comment]
It is set to it. :( "ConanSandbox?Multihome=#144.76.197.233#?GameServerPort=7777?GameServerQueryPort=7778?

**Comment by prom3theu5** [comment]
Can you go in the Updater directory and attach the log file (txt file with todays date) to this post please

**Comment by soerenwa** [comment]
[log-20170209_001.txt](https://github.com/prom3theu5/ConanExilesServerUpdater/files/764081/log-20170209_001.txt)

**Comment by prom3theu5** [comment]
It's not starting it because of an error with your discord settings in config.json.
I see you have Discord Announcement turned on.

Can you please check your discord token, and channelid?
To get the channel ID, in discord, click the gear (settings), go to appearance, and tick the box that says Developer Mode.

Next goto your text channel in discord, right click it and choose copy id.

The discord token is a bot account token, not a widget token.
To get this you have to create and invite a bot account to your server.

Easiest way to do this is [here](https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token)

**Comment by prom3theu5** [comment]
You can test this is the case, by setting AnnounceDiscord to false

**Comment by soerenwa** [comment]
tested it with disabled discord announcement. But the ConanServer error is still here.


[2017.02.09-15.33.01:887][  0]LogOnline:Warning: STEAM: Failed to initialize Steam, this could be due to a Steam server and client running on the same machine.
Try running with -NOSTEAM on the cmdline to disable.
[2017.02.09-15.33.01:887][  0]LogOnline:Display: STEAM: OnlineSubsystemSteam::Shutdown()
[2017.02.09-15.33.01:887][  0]LogOnline:Warning: STEAM: Steam API failed to initialize!
[2017.02.09-15.33.01:887][  0]LogOnline:Display: STEAM: OnlineSubsystemSteam::Shutdown()
[2017.02.09-15.33.01:888][  0]LogInit: WinSock: Socket queue 131072 / 131072
[2017.02.09-15.33.01:890][  0]LogNet:Warning: Failed to init net driver ListenURL: /Game/Maps/ConanSandbox/ConanSandbox?Name=Player?Multihome=?GameServerPort=77
77?GameServerQueryPort=7778?MaxPlayers=40?listen?AdminPassword=?ServerPassword=: WinSock: binding to port 7777 failed (21)
[2017.02.09-15.33.01:890][  0]LogNet: NetworkFailure: NetDriverListenFailure, Error: 'WinSock: binding to port 7777 failed (21)'
[2017.02.09-15.33.01:890][  0]LogOnline:Warning: NULL: Can't destroy a null online session (Game)
[2017.02.09-15.33.01:890][  0]LogWorld: Failed to listen: WinSock: binding to port 7777 failed (21)
[2017.02.09-15.33.01:891][  0]LogNet:Error: LoadMap: failed to Listen(/Game/Maps/ConanSandbox/ConanSandbox?Name=Player?Multihome=?GameServerPort=7777?GameServer
QueryPort=7778?MaxPlayers=40?listen?AdminPassword=?ServerPassword=)
[2017.02.09-15.33.02:234][  0]LogWorld: Bringing World /Game/Maps/ConanSandbox/ConanSandbox.ConanSandbox up for play (max tick rate 0) at 2017.02.09-16.33.02
[2017.02.09-15.33.02:235][  0]LogOnline:Warning: NULL: AutoLogin missing AUTH_LOGIN=<login id>.

**Comment by prom3theu5** [comment]
At least with the Discord Announcing disabled, that won't crash the updater till you get those settings fixed :)

inside startupparameters, after your admin password, can you try adding (SPACE)-nosteamclient

`"StartupParameters": "ConanSandbox?Multihome=#publicip#?GameServerPort=7777?GameServerQueryPort=7778?MaxPlayers=40?listen?AdminPassword=#mypw#?ServerPassword=## -nosteamclient"`

**Comment by prom3theu5** [comment]
that should kill the very first error, and if it still cannot bind the ports, make sure you are running the exiles updater as an admin user or at least one that has permission to bind to network sockets.

The child Process (the server) will inherit permissions from the user of the parent application

**Comment by soerenwa** [comment]
it runs with same privileges as the cmd. I tried to change the port to 27015. The Server got initilazied with gameserverport=27015, but the binding still fails with port 7777. Double checked my config for url port 7777 but nothing. i am a bit clueless right now...

**Comment by Aoxmodeus** [comment]
I recommend this.  Drop to an admin command prompt on the server.  Run netstat -ab and look for a process using port 7777.  Additionally, to work around this problem, here's what I would try.  I'd create a second IP address on the system running the server process.  Then use the -multihome=sec.ond.ary.ip command, and whatever is binding your port 7777 on your original ip won't be an issue.

**Comment by prom3theu5** [comment]
Have you managed to solve your issue Lynoo?

**Comment by Aoxmodeus** [comment]
FYI, this issue has been closed due to no response for troubleshooting.  Lynoo, if you have further issues, please respond to this ticket, and you'll be helped as best as possible.
