### ISSUE TITLE
Do version check on launch if client isn't running already

### ISSUE THREAD

**Issue by YourHuckleberry** [prom3theu5/ConanExilesServerUpdater#5]
Suggestion:
If the Conan application isn't running in the background when the CESU application is launched, do a version check before opening it up instead of launching it - waiting x amount of minutes, and then updating and restarting.

**Comment by prom3theu5** [comment]
Added
New Version: https://github.com/prom3theu5/ConanExilesServerUpdater/releases/download/1.5/1.5.zip
