### ISSUE TITLE
[1.5] Update at Start works, but does not check for updates

### ISSUE THREAD

**Issue by Aoxmodeus** [prom3theu5/ConanExilesServerUpdater#6]
Updated at the start per my config, but I can't get this version to check for updates.

I've got the version in the json set lower than live, and it's not checking, or updating.

**Comment by Aoxmodeus** [comment]
Is there a way to pull down 1.4 compiled?

**Comment by prom3theu5** [comment]
When did you pull the 1.5 version?
There was an issue when I pushed it live, and I replaced the executable about 45 minutes ago.

Can you check now please, as I'm running the new 1.5 on my server

**Comment by prom3theu5** [comment]
In hindsight - I should have pushed it as 1.5.1

**Comment by Aoxmodeus** [comment]
No worries, pulling down now.

**Comment by prom3theu5** [comment]
Thanks :)
There was also a bug with the tasks spawned in the GeneralServices service (Raid settings, and Monitoring server uptime)
They are both fixed too.

**Comment by Aoxmodeus** [comment]
Left for work with it running, came back to Error in Application, and 150 megs worth of log file.  Will capture more data.

**Comment by prom3theu5** [comment]
config.json has changed - can you post me some of the logs please
150mb???

**Comment by Aoxmodeus** [comment]
Started Running 02/09/2017 18:42:25
2017-02-09 10:42:25.539 -08:00 [Information] The "ConanExilesUpdater$ConanExilesUpdater" service is now running, press Control+C to exit.
2017-02-09 10:42:25.581 -08:00 [Information] Starting To Monitor Server is Running
2017-02-09 10:42:26.340 -08:00 [Information] Discord Connected!
2017-02-09 10:47:30.297 -08:00 [Information] Detected SteamVersion as: 1620241. Your version is: "1601110" An Update is required.
2017-02-09 10:47:30.308 -08:00 [Information] Monitor Service has been stopped successfully
2017-02-09 10:47:55.622 -08:00 [Error] Error in Application Monitor: "The operation was canceled."
2017-02-09 10:47:55.625 -08:00 [Error] Error in Application Monitor: "The operation was canceled."
2017-02-09 10:47:55.626 -08:00 [Error] Error in Application Monitor: "The operation was canceled."
2017-02-09 10:47:55.627 -08:00 [Error] Error in Application Monitor: "The operation was canceled."
2017-02-09 10:47:55.627 -08:00 [Error] Error in Application Monitor: "The operation was canceled."
2017-02-09 10:47:55.628 -08:00 [Error] Error in Application Monitor: "The operation was canceled."

**Comment by prom3theu5** [comment]
Ok thanks  -  looks like an issue with task termination in generalservices.
I will debug

**Comment by Aoxmodeus** [comment]
My config.json:

{
  "Twitch": {
    "OAuth": null,
    "Username": null,
    "Channel": null
  },
  "Discord": {
    "DiscordToken": "#REMOVED#",
    "ChannelId": 179624XXXXXX0224
  },
  "Conan": {
    "FolderPath": "e:\\exiles\\",
    "Executable": "ConanSandboxServer.exe",
    "StartupParameters": "Multihome=192.168.50.32 -nosteamclient",
    "RaidingProtectionHoursEnabled": false,
    "RaidingStartHour": 0,
    "RaidingLengthInHours": 0
  },
  "Update": {
    "ShouldInstallSteamCmdIfMissing": false,
    "ShouldInstallConanServerIfMissing": false,
    "SteamCmdPath": "e:\\steamcmd\\",
    "AnnounceDiscord": true,
    "AnnounceTwitch": false,
    "AnnounceMinutesBefore": 5,
    "UpdateCheckInterval": 5,
    "InstalledBuild": 1610241,
    "UpdateOnLaunch": false
  },
  "General": {
    "ShouldRestartConanOnNotRunning": true,
    "RestartServerAfterHours": 6
  }
}

**Comment by Aoxmodeus** [comment]
Sounds good, I'm setting up another update test to see if I can replicate the error.

**Comment by Aoxmodeus** [comment]
Ok, I can replicate the error.  Same issue.  It updates the client, it updates the version listed in the config.json, but then spews errors at a rate of about 20 per millisecond.  Impressive.

**Comment by prom3theu5** [comment]
:D Haha Thanks
https://github.com/prom3theu5/ConanExilesServerUpdater/releases/download/TestTaskFix/TestBuild.zip
Can you give that a test please buddy

**Comment by Aoxmodeus** [comment]
Pulling down now.

**Comment by prom3theu5** [comment]
Thank you :)
Oh thanks so much for the donation - Will get a cold one with it :)

**Comment by Aoxmodeus** [comment]
Ok, you've got success so far on this run.  Launched updater, it saw server process wasn't running, it started it up.  After 1 minute, it alerted our discord that an update was coming in 1 minute.  Then it halted the server process, and after about 1 minute, launched the update, updated the config.json, and relaunched the server process.  I'm getting the console updates now that my version is => steam.  If this restarts the server at the proper interval, I'd say it's clean for a 1.6 release.  Shall we give it an hour and see if it works?  Will the app recognize if I set the restart interval to be say .5 or .1 hour?

**Comment by prom3theu5** [comment]
Awesome
Thanks for that :) 
Unfortunately they are integer values, so has to be whole numbers.
Did the monitoring service start back up after the restart of the server post update?
(I.e. if you crash / close it, does it recover?)

If it did/does, should be ready for a 1.6 release.
Drank far too much coffee today and overlooked a simple issue with the task cancellation tokens :D

**Comment by Aoxmodeus** [comment]
testing server process recovery now

**Comment by Aoxmodeus** [comment]
Server process was restarted cleanly, and is being monitored.  Looks good!

**Comment by prom3theu5** [comment]
Thanks a lot :)
Will merge and push a new release now

**Comment by prom3theu5** [comment]
All sorted :)

https://github.com/prom3theu5/ConanExilesServerUpdater/releases/download/1.6/1.6.zip
