### ISSUE TITLE
[1.6] Small Issue - Version Number in config.json does not update when using update at launch

### ISSUE THREAD

**Issue by Aoxmodeus** [prom3theu5/ConanExilesServerUpdater#8]
In my testing, it looked like when you ran update at launch, if you had an older version, it did not update the build version in the config.json, which would make the updater then shutdown the server and run at the first configured update interval, even if the update at launch updated the server.

**Comment by Aoxmodeus** [comment]
This is confirmed in 1.6.  Update at start does not update config.json version number.

**Comment by prom3theu5** [comment]
Aye you are right, the update on launch is a little dirty - no checks take place.
I'll change this in the next version

**Comment by Aoxmodeus** [comment]
Sounds good.  Not a big issue personally, as I don't feel the need to use that setting, but that other fellow that requested it would probably be happy! 👍

**Comment by prom3theu5** [comment]
Sorted, also included Avatars during certain hours, and an update check against latest github tagged release on startup :)

https://github.com/prom3theu5/ConanExilesServerUpdater/releases/download/1.7/1.7.zip

**Comment by Aoxmodeus** [comment]
Coming up on 1 hour, testing server restart functionality.

**Comment by prom3theu5** [comment]
cool :)

**Comment by Aoxmodeus** [comment]
We're not looking good on the hourly restart.  It's just crossed over into 1 hour of actual "Starting to Monitor Server is Running" and no sign of a reboot.  No message to discord, no stopping of server.

**Comment by Aoxmodeus** [comment]
This is on 1.6.  Updating to 1.7 now.

**Comment by Aoxmodeus** [comment]
Server started 13:22 Pacific.  Will update in 1 hour.

**Comment by Aoxmodeus** [comment]
Ok that was weird.

Where the hell are you checkpointing the running time, or pulling it from?

1.7 just said the server had been up "x amount of time" and restarted it.  NICE!

You must be pulling that from the server process somehow...

Looking good good good, man.

**Comment by Aoxmodeus** [comment]
AoxUpdateBotBOT - Today at 1:23 PM
Conan Server Automatic Restarts are set to run every 1 Hours. The server has been up for 1.04 H 2 M. The Server will restart in 5 Minutes.
Conan Server was not detected as running. Restarting now. The server should show as being online in 2-3 Minutes.

Output to discord.

**Comment by Aoxmodeus** [comment]
Thanks for the app, man, and the quick updates.  Running game servers is more fun to me than actually playing any these games.  Now I should actually accomplish something work related.

**Comment by prom3theu5** [comment]
:) my pleasure buddy

enjoy
